#ifndef __BUTTON_H__
#define __BUTTON_H__

#include "UI.h"

enum class BUTTON_TAG : int
{
	NULL_TAG = -1,

	CLOSE_OPTIONS_MENU,
	CLOSE_CREDITS_MENU,
	CLOSE_SAVE_OK_MENU,

	NEW_GAME,
	CONTINUE_GAME,
	OPTIONS,
	CREDITS,
	EXIT_GAME,

	FULLSCREEN_ON,
	FULLSCREEN_OFF,

	HIDE,
	SHOW,

	PAUSE,
	RESUME,
	MAIN_MENU,
	SAVE,
	LOAD,

	REVIVE_GATHERER,
	REVIVE_MELEE,
	REVIVE_RANGED,
	REVIVE_ROBOTTO,
	BUY_TURRET,
	UPGRADE_TURRET,
	BUY_BARRICADE,
	UPGRADE_BARRICADE,

	GATHERER_LIFE_UPGRADE,
	MELEE_LIFE_UPGRADE,
	RANGED_LIFE_UPGRADE,
	ROBOTTO_LIFE_UPGRADE,
	GATHERER_DAMAGE_UPGRADE,
	MELEE_DAMAGE_UPGRADE,
	RANGED_DAMAGE_UPGRADE,
	ROBOTTO_DAMAGE_UPGRADE,
	GATHERER_ENERGY_UPGRADE,
	MELEE_ENERGY_UPGRADE,
	RANGED_ENERGY_UPGRADE,
	ROBOTTO_ENERGY_UPGRADE,
	GATHERER_ATTACK_SPEED_UPGRADE,
	MELEE_ATTACK_SPEED_UPGRADE,
	RANGED_ATTACK_SPEED_UPGRADE,
	ROBOTTO_ATTACK_SPEED_UPGRADE,

	GATHERER_PASSIVE1,
	MELEE_PASSIVE1,
	RANGED_PASSIVE1,
	ROBOTTO_PASSIVE1,
	GATHERER_ACTIVE1,
	MELEE_ACTIVE1,
	RANGED_ACTIVE1,
	ROBOTTO_ACTIVE1,

	GATHERER_PASSIVE1_UPGRADE,
	MELEE_PASSIVE1_UPGRADE,
	RANGED_PASSIVE1_UPGRADE,
	ROBOTTO_PASSIVE1_UPGRADE,
	GATHERER_ACTIVE1_UPGRADE,
	MELEE_ACTIVE1_UPGRADE,
	RANGED_ACTIVE1_UPGRADE,
	ROBOTTO_ACTIVE1_UPGRADE,

	GATHERER_PORTRAIT,
	MELEE_PORTRAIT,
	RANGED_PORTRAIT,
	ROBO_PORTRAIT,

	NEXT_DIALOG,

};

class Button : public UI
{
public:
	Button(fMPoint positionValue, UI* father, SDL_Rect rect, bool dragable, SDL_Texture* texture, BUTTON_TAG buttonTag, SDL_Rect scaled = {0, 0, 0, 0});
	~Button();

	BUTTON_TAG GetTag();
	void SetTag(BUTTON_TAG tag);

private:
	void HandleInput();
	void Draw(float dt);


private:
	bool clicked;
	bool focusedFirstFrame;
	BUTTON_TAG buttonTag;
	SDL_Rect scaledRect;
};

#endif //__BUTTON_H__