version: 0.3.{build}
branches:
  only:
  - master
skip_tags: true
configuration: Release
build:
  verbosity: minimal


after_build:
- 7z a HoGfromAppVeyor.zip "%APPVEYOR_BUILD_FOLDER%\Proyecto2\Release\Motor 2D.exe"
- 7z a HoGfromAppVeyor.zip "%APPVEYOR_BUILD_FOLDER%\Proyecto2\Game"
- 7z a HoGfromAppVeyor.zip "%APPVEYOR_BUILD_FOLDER%\README.md"

artifacts:
  - path: HoGfromAppVeyor.zip 


## notifications:
 ## - provider: Email
 ##   to:
 ##     - racso2516@gmail.com
 ##  subject: 'Build Success {{buildVersion}}'
  ##  message: "Build Compiles"
  ##  on_build_success: true
  ##  on_build_failure: false
  ##  on_build_status_changed: false
