theme: jekyll-theme-minimal

github:
  logo_url: https://raw.githubusercontent.com/x-mat-studio/HeartsOfGreed/Wiki/General%20Analysis/heartsOfGreed_gameIcon.png
  wiki_url: https://github.com/x-mat-studio/HeartsOfGreed/wiki